# Generated by Django 4.2.13 on 2024-06-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendance_gallery_alter_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
